### ISSUE TITLE
I failed to read data on Android. Do you have any relevant examples？

### ISSUE THREAD

**Issue by nodserve** [s00d/tauri-plugin-serialplugin#8]
I am trying to read data from an electronic scale, which has been implemented on Windows but cannot be used after being packaged as an Android platform. I do not understand Android and Rust. Do you have any examples? Thank you very much.

**Comment by s00d** [comment]
I haven't written any code for Android at all; there are a lot of problems.

I’ve added a test version 2.4.1, but I must warn you right away that almost nothing is likely to work, and the code will need further corrections.

First, to access the devices, you need to list all devices in [device_filter.xml](https://github.com/s00d/tauri-plugin-serialplugin/blob/main/android/src/main/res/xml/device_filter.xml). You should check if your device is in the list; if it’s not, you’ll need to add it. You can do this via a pull request.

Second, the Android code itself can be found [here](https://github.com/s00d/tauri-plugin-serialplugin/tree/main/android). Unfortunately, I don’t work with Kotlin at all, so I generated the code using GPT and rewrote half of it to make it resemble working code, but I haven’t tested it. Also, some methods are commented out, [here](https://github.com/s00d/tauri-plugin-serialplugin/blob/main/android/src/main/kotlin/app/tauri/serialplugin/manager/SerialPortManager.kt). I couldn’t find analogs for them on Android, though they might exist, and if so, we’ll need to add them.

Third, I’m not very confident about the stability of the code, so everything will need to be thoroughly tested.

In general, if you're interested, you can try to run it, test it, and fix any bugs.

---

Also, don't forget to add the repository:  
[android-setup](https://github.com/s00d/tauri-plugin-serialplugin/tree/main?tab=readme-ov-file#android-setup)
